require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MentorsController do

  # This should return the minimal set of attributes required to create a valid
  # Mentor. As you add validations to Mentor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MentorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mentors as @mentors" do
      mentor = Mentor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mentors).should eq([mentor])
    end
  end

  describe "GET show" do
    it "assigns the requested mentor as @mentor" do
      mentor = Mentor.create! valid_attributes
      get :show, {:id => mentor.to_param}, valid_session
      assigns(:mentor).should eq(mentor)
    end
  end

  describe "GET new" do
    it "assigns a new mentor as @mentor" do
      get :new, {}, valid_session
      assigns(:mentor).should be_a_new(Mentor)
    end
  end

  describe "GET edit" do
    it "assigns the requested mentor as @mentor" do
      mentor = Mentor.create! valid_attributes
      get :edit, {:id => mentor.to_param}, valid_session
      assigns(:mentor).should eq(mentor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mentor" do
        expect {
          post :create, {:mentor => valid_attributes}, valid_session
        }.to change(Mentor, :count).by(1)
      end

      it "assigns a newly created mentor as @mentor" do
        post :create, {:mentor => valid_attributes}, valid_session
        assigns(:mentor).should be_a(Mentor)
        assigns(:mentor).should be_persisted
      end

      it "redirects to the created mentor" do
        post :create, {:mentor => valid_attributes}, valid_session
        response.should redirect_to(Mentor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mentor as @mentor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mentor.any_instance.stub(:save).and_return(false)
        post :create, {:mentor => { "user_id" => "invalid value" }}, valid_session
        assigns(:mentor).should be_a_new(Mentor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mentor.any_instance.stub(:save).and_return(false)
        post :create, {:mentor => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mentor" do
        mentor = Mentor.create! valid_attributes
        # Assuming there are no other mentors in the database, this
        # specifies that the Mentor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mentor.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => mentor.to_param, :mentor => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested mentor as @mentor" do
        mentor = Mentor.create! valid_attributes
        put :update, {:id => mentor.to_param, :mentor => valid_attributes}, valid_session
        assigns(:mentor).should eq(mentor)
      end

      it "redirects to the mentor" do
        mentor = Mentor.create! valid_attributes
        put :update, {:id => mentor.to_param, :mentor => valid_attributes}, valid_session
        response.should redirect_to(mentor)
      end
    end

    describe "with invalid params" do
      it "assigns the mentor as @mentor" do
        mentor = Mentor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mentor.any_instance.stub(:save).and_return(false)
        put :update, {:id => mentor.to_param, :mentor => { "user_id" => "invalid value" }}, valid_session
        assigns(:mentor).should eq(mentor)
      end

      it "re-renders the 'edit' template" do
        mentor = Mentor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mentor.any_instance.stub(:save).and_return(false)
        put :update, {:id => mentor.to_param, :mentor => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mentor" do
      mentor = Mentor.create! valid_attributes
      expect {
        delete :destroy, {:id => mentor.to_param}, valid_session
      }.to change(Mentor, :count).by(-1)
    end

    it "redirects to the mentors list" do
      mentor = Mentor.create! valid_attributes
      delete :destroy, {:id => mentor.to_param}, valid_session
      response.should redirect_to(mentors_url)
    end
  end

end
